openapi: 3.0.3
info:
  title: Billing Engine Services
  description: This is a RESTful API documentation.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /:
    get:
      tags:
        - Default
      summary: Root
      responses:
        200:
          $ref: '#/components/responses/200'
  /health:
    get:
      tags:
        - Default
      summary: Check
      responses:
        200:
          $ref: '#/components/responses/healthCheck'
        500:
          $ref: '#/components/responses/500'
  /admin/sign-in:
    post:
      tags:
        - Admin
      summary: Sign in
      requestBody:
        $ref: "#/components/requestBodies/adminSignIn"
      responses:
        200:
          $ref: "#/components/responses/adminSignIn"
        400:
          $ref: "#/components/responses/400"
        500:
          $ref: "#/components/responses/500"
  /admin/sign-out:
    delete:
      tags:
        - Admin
      summary: Sign out
      security:
        - authorize: []
      responses:
        200:
          $ref: "#/components/responses/200"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
  /customer:
    post:
      tags:
        - Customer
      summary: Create
      security:
        - authorize: []
      requestBody:
        $ref: "#/components/requestBodies/customerCreate"
      responses:
        200:
          $ref: "#/components/responses/customerCreate"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
  /loan:
    post:
      tags:
        - Loan
      summary: Create
      security:
        - authorize: []
      requestBody:
        $ref: "#/components/requestBodies/loanCreate"
      responses:
        200:
          $ref: "#/components/responses/loanCreate"
        400:
          $ref: "#/components/responses/400"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
components:
  securitySchemes:
    authorize:
      type: http
      scheme: bearer
  requestBodies:
    adminSignIn:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                default: ""
              password:
                type: string
                default: ""
                minLength: 8
    customerCreate:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                default: ""
              phone_number:
                type: string
                default: ""
                minLength: 10
    loanCreate:
      content:
        application/json:
          schema:
            type: object
            properties:
              customer_id:
                type: integer
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: ok
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: bad request
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: unauthorized
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: internal server error
    adminSignIn:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  token:
                    type: string
                    default: ""
              message:
                type: string
                default: signed in successfully
    customerCreate:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: created successfully
    healthCheck:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: checked successfully
    loanCreate:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: created successfully
