openapi: 3.0.3
info:
  title: Billing Engine Services
  description: This is a RESTful API documentation.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /:
    get:
      tags:
        - Default
      summary: Root
      responses:
        200:
          $ref: '#/components/responses/200'
  /health:
    get:
      tags:
        - Default
      summary: Health Check
      responses:
        200:
          $ref: '#/components/responses/healthCheck'
        500:
          $ref: '#/components/responses/500'
  /admin/sign-in:
    post:
      tags:
        - Admin
      summary: Sign in
      requestBody:
        $ref: "#/components/requestBodies/adminSignIn"
      responses:
        200:
          $ref: "#/components/responses/adminSignIn"
        400:
          $ref: "#/components/responses/400"
        500:
          $ref: "#/components/responses/500"
components:
  requestBodies:
    adminSignIn:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                default: ""
              password:
                type: string
                default: ""
                minLength: 8
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: ok
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: bad request
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: internal server error
    adminSignIn:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  token:
                    type: string
                    default: ""
              message:
                type: string
                default: signed in successfully
    healthCheck:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: string
                nullable: true
                default: null
              message:
                type: string
                default: checked successfully
